// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models.Entity;

public partial class Bank
{
    public long BankId { get; set; }

    public string BankName { get; set; }

    public string BaranchName { get; set; }

    public string Address { get; set; }

    public string IfscCode { get; set; }
}