// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models.Entity;

public partial class BillInstallAmt
{
    public long Id { get; set; }

    public long? PobillId { get; set; }

    public decimal? InstallmentAmt { get; set; }
}