// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models.Entity;

public partial class HtmlTemplate
{
    public long HtmlTemplateId { get; set; }

    public string HtmlType { get; set; }

    public string HtmlTemplate1 { get; set; }
}