// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Models.Entity;

public partial class StockDepartment
{
    public long StockDepartmentId { get; set; }

    public int? UnitId { get; set; }

    public string StockDepartmentName { get; set; }

    public string SdDescription { get; set; }

    public int? CompanyId { get; set; }

    public long? CreatedUid { get; set; }

    public DateOnly? CreateDate { get; set; }

    public bool? IsActive { get; set; }
}